AapWebTools/src/main/java/com/next/aap/web/jsf/beans/AdminCandidateBean.java
package com.next.aap.web.jsf.beans;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.AjaxBehaviorEvent;
import javax.imageio.ImageIO;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.map.MarkerDragEvent;
import org.primefaces.event.map.StateChangeEvent;
import org.primefaces.model.map.DefaultMapModel;
import org.primefaces.model.map.LatLng;
import org.primefaces.model.map.MapModel;
import org.primefaces.model.map.Marker;

import com.google.gdata.util.common.base.StringUtil;
import com.next.aap.core.exception.AppException;
import com.next.aap.core.util.MyaapInUtil;
import com.next.aap.web.cache.CandidateCacheImpl;
import com.next.aap.web.cache.LocationCacheDbImpl;
import com.next.aap.web.dto.AppPermission;
import com.next.aap.web.dto.AssemblyConstituencyDto;
import com.next.aap.web.dto.CandidateDto;
import com.next.aap.web.dto.ElectionDto;
import com.next.aap.web.dto.LocationCampaignDto;
import com.next.aap.web.dto.LoginAccountDto;
import com.next.aap.web.dto.ParliamentConstituencyDto;
import com.next.aap.web.dto.StateDto;
import com.next.aap.web.dto.UserDto;
import com.next.aap.web.util.AwsImageUploadUtil;
import com.next.aap.web.util.AwsImageUtil;
import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLBeanName;
import com.ocpsoft.pretty.faces.annotation.URLMapping;

@ManagedBean
@SessionScoped
@URLMapping(id = "adminCandidateBean", beanName = "adminCandidateBean", pattern = "/admin/candidate", viewId = "/WEB-INF/jsf/admin_candidate.xhtml")
@URLBeanName("adminCandidateBean")
public class AdminCandidateBean extends BaseAdminJsfBean {

	private static final long serialVersionUID = 1L;

	private CandidateDto candidate = new CandidateDto();
	
	List<CandidateDto> candidates;

    List<ElectionDto> elections;

	private boolean showList = true;
    private boolean showPc = false;
    private boolean showAc = false;
	private boolean enablePcBox = false;
    private boolean enableAcBox = false;
	private boolean formEditable = false;
    private String urlMidPart = "";
    private Long selectedElectionId;
	
	private String baseUrl = "http://my.aamaadmiparty.org";
	private String baseDonationUrl="https://donate.aamaadmiparty.org?utm_source=myaap&utm_medium=web&utm_term=donate-url&utm_content=donation&utm_campaign=candidate";
	//private String baseDonationUrl1="https://donate.aamaadmiparty.org/?State=UP&Loksabha=435";
	
	@ManagedProperty("#{candidateCacheImpl}")
	protected CandidateCacheImpl candidateCacheImpl;
	
	@ManagedProperty("#{locationCacheDbImpl}")
	private LocationCacheDbImpl locationCacheDbImpl;
	
	@ManagedProperty("#{awsImageUtil}")
	private AwsImageUtil awsImageUtil;
	
	@ManagedProperty("#{awsImageUploadUtil}")
	private AwsImageUploadUtil awsImageUploadUtil;
	

	@ManagedProperty("#{myaapInUtil}")
	private MyaapInUtil myaapInUtil;
	
	
	List<StateDto> stateList;
	
	static Pattern myPattern = Pattern.compile("^[a-zA-Z0-9]+$");
	
	private MapModel draggableMapModel;

	Marker marker;

    private static double defaultLattitude = 28.5890399;
    private static double defaultLongitude = 77.245964;
    private static int defaultDepth = 10;

	public AdminCandidateBean() {
		super(AppPermission.ADMIN_CANDIDATE_PC, "/admin/candidate");
	}
	public static BufferedImage resize(BufferedImage img, int newW, int newH) {  
        int w = img.getWidth();  
        int h = img.getHeight();  
        BufferedImage dimg = dimg = new BufferedImage(newW, newH, img.getType());  
        Graphics2D g = dimg.createGraphics();  
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);  
        g.drawImage(img, 0, 0, newW, newH, 0, 0, w, h, null);  
        g.dispose();  
        return dimg;  
    }  
	public void handleFileUpload(FileUploadEvent event) {  
		//.
		
		System.out.println("event.getFileName()" +event.getFile().getFileName());
		System.out.println("event.getContentType()" +event.getFile().getContentType());
		System.out.println("event.getSize()" +event.getFile().getSize());
		logger.info("event.getFileName()" +event.getFile().getFileName());
		logger.info("event.getContentType()" +event.getFile().getContentType());
		logger.info("event.getSize()" +event.getFile().getSize());
		logger.info("awsImageUtil=" +awsImageUtil+",myaapInUtil="+myaapInUtil);
		logger.info("awsImageUploadUtil=" +awsImageUploadUtil+",myaapInUtil="+myaapInUtil);
		
		String imageType = ".jpg";
		if("image/png".equals(event.getFile().getContentType())){
			imageType = ".png";
		}
		if("image/jpeg".equals(event.getFile().getContentType())){
			imageType = ".jpg";
		}
		String remoteFileName = candidate.getId() + imageType;
			try {
				String httpFilePath = awsImageUtil.uploadCandidateProfileImage(remoteFileName, event.getFile().getInputstream());
				candidate.setImageUrl(httpFilePath);
				
				candidate.setImageUrl64(createAndUploadIcons(event.getFile().getInputstream(), imageType, 64));
				candidate.setImageUrl32(createAndUploadIcons(event.getFile().getInputstream(), imageType, 32));
				System.out.println("handleFileUpload:candidateDto.getImageUrl64()="+candidate.getImageUrl64());
				System.out.println("handleFileUpload:candidateDto.getImageUrl32()="+candidate.getImageUrl32());

				candidate = aapService.saveCandidate(candidate);
				System.out.println("httpFilePath = " +httpFilePath);
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} catch (IOException e) {
				e.printStackTrace();
			} catch (AppException e) {
				e.printStackTrace();
			}
        FacesMessage msg = new FacesMessage("Succesful", event.getFile().getFileName() + " is uploaded.");  
        FacesContext.getCurrentInstance().addMessage(null, msg);  
    }  
	private String createAndUploadIcons(InputStream is,String imageType, int size) throws IOException, AppException{
		BufferedImage bufferedImage = ImageIO.read(is);
		BufferedImage iconImage = resize(bufferedImage, size, size);
		String remoteIconFileName = candidate.getId()+"_"+size+imageType;
		String localIconFileNameAndPath = "/tmp/"+remoteIconFileName;
		ImageIO.write(iconImage, "png", new FileOutputStream(localIconFileNameAndPath));
		String httpFilePath = awsImageUtil.uploadCandidateProfileImage(remoteIconFileName, new FileInputStream(localIconFileNameAndPath));
		System.out.println("createAndUploadIcons : httpFilePath = " +httpFilePath);
		return httpFilePath;
	}
	public boolean isFileUploadDisabled(){
		if(candidate.getId() == null || candidate.getId() <= 0){
			return true;
		}
		return false;
	}

	// @URLActions(actions = { @URLAction(mappingId = "userProfileBean") })
	@URLAction(onPostback = false)
	public void init() throws Exception {

		if (!checkUserAccess()) {
			return;
		}

		try {
			draggableMapModel = new DefaultMapModel();

			LatLng coord1 = new LatLng(defaultLattitude, defaultLongitude);
			// Draggable
			marker = new Marker(coord1, "Candidate Location");
			marker.setDraggable(true);
			draggableMapModel.addOverlay(marker);

			candidate.setLattitude(defaultLattitude);
			candidate.setLongitude(defaultLongitude);
			candidate.setDepth(defaultDepth);
			
            elections = aapService.getAllElections();
			stateList = locationCacheDbImpl.getAllStates();
			
            // refreshCandidates();
		} catch (Exception ex) {
			sendErrorMessageToJsfScreen(ex);
		}

	}

    public void handleElectionChange(AjaxBehaviorEvent event) {
        candidate.setElectionId(selectedElectionId);
        refreshCandidates();
    }

    public void handleCandidateTypeChange(AjaxBehaviorEvent event) {
        showPc = false;
        showAc = false;

        urlMidPart = "/";
        if ("MLA".equalsIgnoreCase(candidate.getCandidateType())) {
            showAc = true;
            formEditable = true;
            urlMidPart = "/ac/";
        } else if ("MP".equalsIgnoreCase(candidate.getCandidateType())) {
            showPc = true;
            formEditable = true;
        } else {
            formEditable = false;
        }
    }
	public void handleStateChange(AjaxBehaviorEvent event) {
		try {
			if (candidate.getStateId() == null || candidate.getStateId() <= 0) {
				enablePcBox = false;
                enableAcBox = false;
			} else {
				enablePcBox = true;
                enableAcBox = true;
			}
			formEditable = false;
		} catch (Exception e) {
			e.printStackTrace();
		}
	}	
	public static void main(String[] args){
		String selectedStateName = "Ambaba (sc)";
		selectedStateName = selectedStateName.replaceAll("\\(sc\\)" , "");
		System.out.println(selectedStateName);
	}
	public void handlePcChange(AjaxBehaviorEvent event) {
		try {
			if (candidate.getParliamentConstituencyId() == null || candidate.getParliamentConstituencyId() <= 0) {
				formEditable = false;
			} else {
				formEditable = true;
                CandidateDto existingCandidate = aapService.getCandidateByPcIdAndElectionId(candidate.getParliamentConstituencyId(), candidate.getElectionId());
				if(existingCandidate != null){
					candidate = existingCandidate;
				}else{
					CandidateDto selectedCandidate = candidate;
					candidate = new CandidateDto();
					candidate.setStateId(selectedCandidate.getStateId());
                    candidate.setCandidateType(selectedCandidate.getCandidateType());
                    candidate.setElectionId(selectedElectionId);
					candidate.setParliamentConstituencyId(selectedCandidate.getParliamentConstituencyId());

AapWebTools/src/main/java/com/next/aap/web/jsf/beans/AdminEditOfficeDetailBean.java
package com.next.aap.web.jsf.beans;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.primefaces.event.map.MarkerDragEvent;
import org.primefaces.event.map.StateChangeEvent;
import org.primefaces.model.map.DefaultMapModel;
import org.primefaces.model.map.LatLng;
import org.primefaces.model.map.MapModel;
import org.primefaces.model.map.Marker;

import com.next.aap.web.dto.AppPermission;
import com.next.aap.web.dto.LoginAccountDto;
import com.next.aap.web.dto.OfficeDto;
import com.next.aap.web.dto.UserDto;
import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLBeanName;
import com.ocpsoft.pretty.faces.annotation.URLMapping;

@ManagedBean
@ViewScoped
@URLMapping(id = "adminEditOfficeDetailBean", beanName = "adminEditOfficeDetailBean", pattern = "/admin/office", viewId = "/WEB-INF/jsf/admin_office.xhtml")
@URLBeanName("adminEditOfficeDetailBean")
public class AdminEditOfficeDetailBean extends BaseMultiPermissionAdminJsfBean {

	private static final long serialVersionUID = 1L;

	private OfficeDto selectedOffice;

	private boolean showList = true;
	
	private static double defaultLattitude = 23.2411685061471;
	private static double defaultLongitude = 77.4254605000001;
	
	private MapModel draggableMapModel;
	
	Marker marker;

	private List<OfficeDto> officeList;

	public AdminEditOfficeDetailBean() {
		super("/admin/office", AppPermission.EDIT_OFFICE_ADDRESS);
	}

	// @URLActions(actions = { @URLAction(mappingId = "userProfileBean") })
	@URLAction(onPostback = false)
	public void init() throws Exception {
		if (!checkUserAccess()) {
			return;
		}
		refreshNewsList();
		draggableMapModel = new DefaultMapModel();
		
		LatLng coord1 = new LatLng(selectedOffice.getLattitude(), selectedOffice.getLongitude()); 
        //Draggable  
		marker = new Marker(coord1, "Office Location");
		marker.setDraggable(true);
		draggableMapModel.addOverlay(marker);  
	}
	
	public void onMarkerDrag(MarkerDragEvent event) {  
        marker = event.getMarker();  
    }  
	public void onStateChange(StateChangeEvent event) {
		selectedOffice.setDepth(event.getZoomLevel());
    }  

	private void refreshNewsList() {
		officeList = aapService.getLocationOffices(menuBean.getLocationType(), menuBean.getAdminSelectedLocationId());
		if (officeList == null || officeList.size() <= 1) {
			if (officeList.size() == 1) {
				selectedOffice = officeList.get(0);
			} else {
				selectedOffice = new OfficeDto();
				selectedOffice.setLattitude(defaultLattitude);
				selectedOffice.setLongitude(defaultLongitude);
				selectedOffice.setDepth(10);
			}
			showList = false;
		}
	}

	public LoginAccountDto getLoginAccounts() {
		return getLoggedInAccountsFromSesion();
	}

	public UserDto getUser() {
		return getLoggedInUser();
	}

	public void saveOfficeDetail() {
		selectedOffice.setLattitude(marker.getLatlng().getLat());
		selectedOffice.setLongitude(marker.getLatlng().getLng());
		try {
			switch (menuBean.getLocationType()) {
			case Global:
				selectedOffice.setNational(true);
				break;
			case STATE:
				selectedOffice.setStateId(menuBean.getAdminSelectedLocationId());
				break;
			case DISTRICT:
				selectedOffice.setDistrictId(menuBean.getAdminSelectedLocationId());
				break;
			case AC:
				selectedOffice.setAssemblyConstituencyId(menuBean.getAdminSelectedLocationId());
				break;
			case PC:
				selectedOffice.setParliamentConstituencyId(menuBean.getAdminSelectedLocationId());
				break;
			case COUNTRY:
				selectedOffice.setCountryId(menuBean.getAdminSelectedLocationId());
				break;
			case REGION:
				selectedOffice.setCountryRegionId(menuBean.getAdminSelectedLocationId());
				break;
			case AREA:
				selectedOffice.setCountryRegionAreaId(menuBean.getAdminSelectedLocationId());
				break;
			default:
				sendErrorMessageToJsfScreen("No Location selected");
			}
			if (isValidInput()) {
				selectedOffice = aapService.saveOffice(selectedOffice);
				sendInfoMessageToJsfScreen("Office Details saved Succesfully");
				refreshNewsList();
			}
		} catch (Exception ex) {
			sendErrorMessageToJsfScreen("Unable to save Office Detail", ex);
		}
	}

	public boolean isShowList() {
		return showList;
	}

	public void setShowList(boolean showList) {
		this.showList = showList;
	}

	public OfficeDto getSelectedOffice() {
		return selectedOffice;
	}

	public void setSelectedoffice(OfficeDto selectedoffice) {
		this.selectedOffice = selectedoffice;
		showList = false;
	}

	public List<OfficeDto> getOfficeList() {
		return officeList;
	}

	public void setOfficeList(List<OfficeDto> officeList) {
		this.officeList = officeList;
	}

	public MapModel getDraggableMapModel() {
		return draggableMapModel;
	}

	public void setDraggableMapModel(MapModel draggableMapModel) {
		this.draggableMapModel = draggableMapModel;
	}

}

AapWebTools/src/main/java/com/next/aap/web/jsf/beans/AdminNotAllowedBean.java
package com.next.aap.web.jsf.beans;

import javax.faces.bean.ViewScoped;

import org.springframework.stereotype.Component;

import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLBeanName;
import com.ocpsoft.pretty.faces.annotation.URLMapping;

@Component
//@Scope("session")
@ViewScoped
@URLMapping(id = "adminNotAllowedBean", beanName="adminNotAllowedBean", pattern = "/admin/notallowed", viewId = "/WEB-INF/jsf/admin_not_allowed.xhtml")
@URLBeanName("adminNotAllowedBean")
public class AdminNotAllowedBean extends BaseJsfBean {

	private static final long serialVersionUID = 1L;

	//@URLActions(actions = { @URLAction(mappingId = "userProfileBean") })
	@URLAction(onPostback=false)
	public void init() throws Exception {
	}

}

AapWebTools/src/main/java/com/next/aap/web/jsf/beans/BaseAdminJsfBean.java
package com.next.aap.web.jsf.beans;

import javax.faces.bean.ManagedProperty;

import org.springframework.beans.factory.annotation.Autowired;

import com.next.aap.core.service.AapService;
import com.next.aap.web.dto.AppPermission;
import com.next.aap.web.dto.UserDto;
import com.next.aap.web.dto.UserRolePermissionDto;
import com.next.aap.web.util.ClientPermissionUtil;

public class BaseAdminJsfBean extends BaseJsfBean{

	@ManagedProperty("#{aapService}")
	protected AapService aapService;
	
	@ManagedProperty("#{menuBean}")
	protected MenuBean menuBean;

	AppPermission appPermission;
	String url;
	public BaseAdminJsfBean(AppPermission appPermission, String url){
		this.appPermission = appPermission;
		this.url = url;
	}
	protected boolean checkUserAccess(){
		UserDto loggedInUser = getLoggedInUser(true,buildLoginUrl(url));
		if(loggedInUser == null){
			return false;
		}
		if(isLocationNotSelected(menuBean)){
			buildAndRedirect("/admin/home");
			return false;
		}

		UserRolePermissionDto userRolePermissionDto = getUserRolePermissionInSesion();
		if(!ClientPermissionUtil.isAllowed(appPermission, userRolePermissionDto, menuBean.getAdminSelectedLocationId(), menuBean.getLocationType())){
			buildAndRedirect("/admin/notallowed");
			return false;
		}
		return true;
	}
	public MenuBean getMenuBean() {
		return menuBean;
	}
	public void setMenuBean(MenuBean menuBean) {
		this.menuBean = menuBean;
	}
	public AapService getAapService() {
		return aapService;
	}
	public void setAapService(AapService aapService) {
		this.aapService = aapService;
	}
}

AapWebTools/src/main/webapp/WEB-INF/jsf/aapstyle/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<div class="banner">
		<img src="https://lh6.googleusercontent.com/-tAPN3HAM2L8/Us8DLZohQ-I/AAAAAAAANwY/5CX8FZ0PYuo/s960/banner.jpg" />
	</div>
	<div class="top-row">
		<div class="profile-pic">
			<img src="#{menuBean.user.profilePic}?type=large" />
		</div>
		<div class="menubar">
			<div id='cssmenu'>
				<ul>

					<li><a href='/home'><span>Home</span></a></li>
					
						<li class='has-sub'><a href='#'><span>Donations</span></a>
						<ul>
							<li><a href='/mydonations'><span>My Donation</span></a></li>
							<li class='last'><a href='/ripple'><span>Ripple</span></a></li>
						</ul></li>
					<li class='has-sub'><a href='/profile'><span>Profile</span></a>
						<ul>
							<li><a href='/socialaccounts'><span>Social Accounts</span></a></li>
							<li class='last'><a href='/profile'><span>Edit Profile</span></a></li>
							<li class='last'><a href='/volunteer'><span>Volunteer Profile</span></a></li>
						</ul></li>
						<li class='has-sub'><a href='/voiceofaap'><span>Voice of AAP</span></a>
						<ul>
							<li><a href='/voiceofaap'><span>Settings</span></a></li>
							<li class='last'><a href='/voafactivity'><span>Activity</span></a></li>
						</ul></li>
					<li><a href='/contactus'><span>Contact Us</span></a></li>
					<li><a href='/admin/home'><p:outputPanel rendered="#{menuBean.admin}"><span>Admin</span></p:outputPanel></a></li>
					<li class='last'><a href='/logout'><p:outputPanel rendered="#{menuBean.loggedIn}"><span>Sign Out</span></p:outputPanel></a></li>
					
				</ul>
			</div>
		</div>
	</div>
	<div class="profile-name">
		#{menuBean.user.name} <br />
		<p:outputPanel rendered="#{menuBean.user.member}">Member<br />
		#{menuBean.user.membershipNumber}
		</p:outputPanel>
		
	</div>


</ui:composition>

AapWebTools/src/main/webapp/WEB-INF/jsf/aapstyle/home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
<ui:include src="htmlhead.xhtml" />
<title>#{menuBean.user.name} - Home</title>
</h:head>
<h:body>

	<div class="body">
		<ui:include src="header.xhtml" />
		<div class="bottom-row">
			<ui:include src="leftwidget.xhtml" />
			<div class="social-area">
				<div class="social-fb">
					
				</div>
				<div class="social-twtr">
					
				</div>
			</div>
		</div>
	</div>
	<ui:include src="footer.xhtml" />
	
	
</h:body>
</html>

AapWebTools/src/main/webapp/WEB-INF/jsf/aapstyle/leftwidget.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<script type="text/javascript">
    function goToDonationPage(){
        window.location = "https://donate.aamaadmiparty.org/";
    }
    function goToVoiceOfAppPage(){
        window.location = "/volunteer";
    }
    function goToVolunteerPage(){
        window.location = "/volunteer";
    }
</script>
	<div class="widgets">
		<div class="left-widget" onclick="inviteFriendsToJoin()">
			<p>Invite Friends</p>
		</div>

		<div class="left-widget" onclick="goToDonationPage()">
			<p>Donate</p>
		</div>

		<div class="left-widget" onclick="goToVoiceOfAppPage()">
			<p>Voice of AAP</p>
		</div>

		<div class="left-widget" onclick="goToVolunteerPage()">
			<p>Become Volunteer</p>
		</div>
	</div>

</ui:composition>

AapWebTools/src/main/webapp/WEB-INF/jsf/aapstyle/socialaccounts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
<ui:include src="htmlhead.xhtml" />
	<title>Social Accounts</title>
</h:head>
<h:body>

	<div class="body">
		<ui:include src="header.xhtml" />

		<div class="bottom-row">
			<ui:include src="leftwidget.xhtml" />
			<div class="social-area">
				<h:panelGrid columns="2" styleClass="topAlignPanelColumns">
					<p:fieldset>
						<f:facet name="legend">
							<div class="topAlignDiv">
								<p:graphicImage value="https://cdn4.iconfinder.com/data/icons/circle-network/52/twitter_social_circle-20.png" />
								Twitter Connections
							</div>
						</f:facet>

						<p:dataGrid styleClass="topAlignPanelColumns" var="oneTwitterAccount" value="#{socialAccountBean.loginAccounts.twitterAccounts}" columns="2" paginator="false"
							emptyMessage="No Twitter Account connected">
							<p:graphicImage value="#{oneTwitterAccount.imageUrl}" styleClass="facebook-data-row" />
							<h:outputText value="#{oneTwitterAccount.screenName}" style="font-size:18px;font-style:bold;" />
						</p:dataGrid>
						<br></br>
				Add Twitter Account<br></br>

						<a href="./login/twitter" class="twitter"></a>
						<em style="font-size: 10px;">you can add multiple twitter accounts to your AAP account</em>
					</p:fieldset>
					<p:fieldset>
						<f:facet name="legend">
							<div class="topAlignDiv">
								<p:graphicImage value="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/facebook_circle_color-20.png" />
								Facebook Connections
							</div>
						</f:facet>

						<p:dataGrid styleClass="topAlignPanelColumns" var="oneFacebookAccount" value="#{socialAccountBean.loginAccounts.facebookAccounts}" columns="2" paginator="false"
							emptyMessage="No Facebook Account connected">
							<p:graphicImage value="#{oneFacebookAccount.imageUrl}" />
							<h:outputText value="#{oneFacebookAccount.userName}" />
						</p:dataGrid>
						<br></br>
						<p:outputPanel rendered="#{socialAccountBean.renderFacebookConnectionButton}">
					Add Facebook Account
					<a href="./login/facebook" class="facebook"></a>
						</p:outputPanel>
						<p:outputPanel rendered="#{!socialAccountBean.renderFacebookConnectionButton}">
							<em style="font-size: 10px;">you can add only one facebook account to your AAP account</em>
						</p:outputPanel>
					</p:fieldset>
					<br></br>
					<br></br>
					<br></br>
					<br></br>
				</h:panelGrid>
			</div>
		</div>
	</div>
	<ui:include src="footer.xhtml" />
</h:body>
</html>

AapWebTools/src/main/webapp/WEB-INF/jsf/aapstyle/uservolunteerprofile.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<ui:include src="htmlhead.xhtml" />
	<title>Social Accounts</title>
</h:head>
<h:body>

	<div class="body">
		<ui:include src="header.xhtml" />

		<div class="bottom-row">
			<ui:include src="leftwidget.xhtml" />
			<div class="social-area">
				<h:form id="userVolunteerForm">
				<h:panelGrid>
				<p:messages autoUpdate="true" />
				<ui:include src="../common/volunteer.xhtml" >
					<ui:param name="param_VolunteerBean" value="#{userVolunteerBean.volunteerBean}" />
				</ui:include>


					<p:commandButton id="saveProfile" value="Save Volunteer Profile" actionListener="#{userVolunteerBean.saveProfile}" />
					<p:tooltip for="saveProfile">Save Profile</p:tooltip>

				</h:panelGrid>
				</h:form>
			</div>
		</div>
	</div>
	<ui:include src="footer.xhtml" />
</h:body>
</html>